[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "agent_platform"
version = "0.1.0"
description = "A platform for managing and running AI agents"
requires-python = ">=3.8"
